Iss1828 - Add GitHub workflows as overlays for the mono repo and adjust script
galasa-dev/mono-repo-creator pull request #1
Opened 2024-10-21 14:19 UTC by jadecarino

## Why?

For https://github.com/galasa-dev/projectmanagement/issues/1828

GitHub workflows added into the overlays folder so they are added into the mono repo on top of the modules.
Adjustments made to script to ensure hidden folder `.github` is copied over into the overlays.
Removed CLI from the script as we are not adding it into the mono repo yet.

2024-11-01 10:17 UTC, eamansour approved these changes

2024-11-01 17:42 UTC, techcobweb commented on overlays/tools/get-changed-modules-pull-request.sh
> +module_names=(\
This list could be dynamically calculated by listing the folders in the `modules` folder ? Then adding or removing a new module wouldn't need this script to change ?

2024-11-01 17:44 UTC, techcobweb commented on overlays/tools/get-changed-modules-pull-request.sh
> +        if [[ "$module" == "wrapping" ]]; then
The env var could be built dynamically using the module name ? So adding or removing a module need not require changes to this script in future.

2024-11-01 17:44 UTC, techcobweb commented on overlays/tools/get-changed-modules-push.sh
> +module_names=(\
same comment as above.

2024-11-01 17:45 UTC, techcobweb commented on overlays/tools/get-changed-modules-push.sh
> +        if [[ "$module" == "buildutils" ]]; then
same comment as above.

If this is a duplicate function, I would put it into a second script and call that ?

2024-11-01 17:46 UTC, techcobweb commented on overlays/tools/get-last-successful-workflow-run-for-artifacts.sh
> +get_last_successful_workflow_id openapi2beans "Buildutils is unchanged"
Not sure whether this could be made more dynamic. Probably.

2024-11-01 17:47 UTC, techcobweb requested changes
I've added some comments, but if it works, these could be transferred to a new improvement story, and this one delivered ?

2024-11-04 09:54 UTC, techcobweb approved these changes

2024-11-04 09:59 UTC, techcobweb approved these changes

2024-11-04 10:00 UTC, merged